# Date : 29/09/2026
# Auteurs : Elpidio Alexis AMOUSSOU
#           Eli Yannick HOVI
# Emails : amoussouelpidioalexis@gmail.com
#          yannickeli2007@gmail.com
# But : Propriétés JVM et options de configuration de compilation Gradle pour Android.

org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
